import { StyleSheet } from 'react-native';

export const createAuthStyles = (colors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      padding: 16,
      backgroundColor: colors.background,
      justifyContent: 'center',
    },
    authCard: {
      backgroundColor: colors.surface,
      padding: 18,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: '#111827',
      shadowOpacity: 0.09,
      shadowRadius: 14,
      elevation: 6,
    },
    title: {
      fontSize: 24,
      fontWeight: '900',
      marginBottom: 4,
      color: colors.text,
    },
    subtitle: {
      fontSize: 13,
      fontWeight: '600',
      marginBottom: 18,
      color: colors.muted,
    },
    label: {
      fontSize: 11,
      fontWeight: '700',
      marginBottom: 6,
      color: colors.muted,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
    },
    input: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 14,
      backgroundColor: colors.surface,
      fontSize: 15,
      color: colors.text,
    },
  });

export const createDashboardStyles = (colors) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: colors.background },
    scrollContent: { paddingHorizontal: 16, paddingTop: 14, paddingBottom: 130 },
    topRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 },
    eyebrow: { color: colors.muted, fontSize: 12, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.6 },
    brandTitle: { marginTop: 4, color: colors.text, fontSize: 28, fontWeight: '800' },
    profileHandle: { marginTop: 4, color: colors.muted, fontSize: 12, fontWeight: '700' },
    avatarRing: { width: 52, height: 52, borderRadius: 26, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.secondary, padding: 2 },
    avatarInner: { width: 46, height: 46, borderRadius: 23, backgroundColor: colors.surface, justifyContent: 'center', alignItems: 'center' },
    avatarText: { fontSize: 14, fontWeight: '900', color: colors.primary },
    heroCard: { borderRadius: 24, backgroundColor: colors.primary, paddingHorizontal: 18, paddingVertical: 18, marginBottom: 20, overflow: 'hidden' },
    heroGlowLeft: { position: 'absolute', width: 170, height: 170, borderRadius: 90, opacity: 0.35, top: -60, left: -40 },
    heroGlowRight: { position: 'absolute', width: 180, height: 180, borderRadius: 90, opacity: 0.33, bottom: -80, right: -50 },
    heroCaption: { fontSize: 11, color: 'rgba(255,255,255,0.84)', fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.8 },
    heroAmount: { fontSize: 30, color: colors.onPrimary, fontWeight: '900', marginTop: 8 },
    heroHint: { marginTop: 6, color: 'rgba(255,255,255,0.84)', fontSize: 12 },
    heroStatsRow: { marginTop: 16, flexDirection: 'row', gap: 10 },
    heroPill: { flex: 1, backgroundColor: 'rgba(255,255,255,0.17)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.28)', borderRadius: 14, padding: 10 },
    heroPillLabel: { fontSize: 10, fontWeight: '700', color: 'rgba(255,255,255,0.88)', textTransform: 'uppercase', letterSpacing: 0.6 },
    heroPillValue: { marginTop: 4, fontSize: 14, fontWeight: '800', color: colors.onPrimary },
    sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
    sectionTitle: { fontSize: 15, fontWeight: '800', color: colors.text },
    sectionLink: { fontSize: 12, fontWeight: '700', color: colors.primary },
    quickActionsGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', marginBottom: 18 },
    quickCard: { width: '48.5%', borderRadius: 18, paddingHorizontal: 14, paddingVertical: 14, marginBottom: 10, borderWidth: 1, borderColor: colors.border },
    quickCardTitle: { color: colors.text, fontSize: 14, fontWeight: '800' },
    quickCardSubtitle: { marginTop: 4, color: colors.muted, fontSize: 12 },
    snapshotRow: { flexDirection: 'row', gap: 10, marginBottom: 18 },
    snapshotCard: { flex: 1, backgroundColor: colors.surface, borderRadius: 16, borderWidth: 1, borderColor: colors.border, padding: 12 },
    snapshotLabel: { color: colors.muted, fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.6 },
    snapshotValue: { marginTop: 6, color: colors.text, fontSize: 16, fontWeight: '800' },
    transactionCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surface, borderRadius: 16, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 12, paddingVertical: 12, marginBottom: 9 },
    dot: { width: 10, height: 10, borderRadius: 5, marginRight: 10 },
    transactionTitle: { color: colors.text, fontSize: 13, fontWeight: '800' },
    transactionMeta: { marginTop: 3, color: colors.muted, fontSize: 11 },
    transactionAmount: { fontSize: 12, fontWeight: '700', color: colors.primary, marginLeft: 8 },
    emptyState: { backgroundColor: colors.surface, borderRadius: 16, borderWidth: 1, borderColor: colors.border, padding: 16 },
    emptyTitle: { fontSize: 13, fontWeight: '800', color: colors.text },
    emptyText: { marginTop: 6, fontSize: 12, color: colors.muted },
  });

export const createIncomeStyles = (colors) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: colors.background },
    scrollContent: { paddingHorizontal: 16, paddingTop: 14, paddingBottom: 30 },
    heroCard: { borderRadius: 24, backgroundColor: colors.primary, paddingHorizontal: 16, paddingVertical: 16, overflow: 'hidden', marginBottom: 12 },
    heroGlowOne: { position: 'absolute', width: 170, height: 170, borderRadius: 85, top: -90, left: -44, opacity: 0.4 },
    heroGlowTwo: { position: 'absolute', width: 170, height: 170, borderRadius: 85, bottom: -88, right: -36, opacity: 0.35 },
    heroCaption: { color: 'rgba(255,255,255,0.84)', fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.7 },
    heroTitle: { marginTop: 5, color: colors.onPrimary, fontSize: 22, fontWeight: '900' },
    heroMeta: { marginTop: 5, color: 'rgba(255,255,255,0.85)', fontSize: 12 },
    heroPill: { marginTop: 12, borderRadius: 14, padding: 10, backgroundColor: 'rgba(255,255,255,0.18)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.28)' },
    heroPillLabel: { color: 'rgba(255,255,255,0.88)', fontSize: 10, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.7 },
    heroPillValue: { marginTop: 5, color: colors.onPrimary, fontSize: 18, fontWeight: '900' },
    heroPillHint: { marginTop: 4, color: 'rgba(255,255,255,0.85)', fontSize: 11 },
    card: { borderRadius: 20, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, padding: 14 },
    fieldLabel: { fontSize: 12, fontWeight: '700', color: colors.text, marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.6 },
    input: { borderRadius: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, color: colors.text, paddingHorizontal: 12, paddingVertical: 11, fontSize: 14, marginBottom: 10 },
    quickGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', marginBottom: 12 },
    quickChip: { width: '23%', backgroundColor: colors.primarySoft, paddingVertical: 9, borderRadius: 10, borderWidth: 1, borderColor: colors.primary, alignItems: 'center' },
    quickChipText: { color: colors.onSoft, fontWeight: '800', fontSize: 12 },
    footerNote: { textAlign: 'center', marginTop: 12, color: colors.muted, fontSize: 12 },
  });

export const createExpensesStyles = (colors) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: colors.background },
    scrollContent: { paddingHorizontal: 16, paddingTop: 14, paddingBottom: 120 },
    heroCard: { borderRadius: 24, backgroundColor: colors.primary, paddingHorizontal: 16, paddingVertical: 16, overflow: 'hidden', marginBottom: 12 },
    heroGlowOne: { position: 'absolute', width: 170, height: 170, borderRadius: 85, top: -90, left: -44, opacity: 0.4 },
    heroGlowTwo: { position: 'absolute', width: 170, height: 170, borderRadius: 85, bottom: -88, right: -36, opacity: 0.35 },
    heroCaption: { color: 'rgba(255,255,255,0.84)', fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.7 },
    heroTitle: { marginTop: 5, color: colors.onPrimary, fontSize: 22, fontWeight: '900' },
    heroMeta: { marginTop: 5, color: 'rgba(255,255,255,0.85)', fontSize: 12 },
    heroPill: { marginTop: 12, borderRadius: 14, padding: 10, backgroundColor: 'rgba(255,255,255,0.17)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.28)' },
    heroPillLabel: { color: 'rgba(255,255,255,0.88)', fontSize: 10, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.7 },
    heroPillValue: { marginTop: 5, color: colors.onPrimary, fontSize: 16, fontWeight: '900' },
    card: { borderRadius: 20, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, padding: 14 },
    fieldLabel: { fontSize: 12, fontWeight: '700', color: colors.text, marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.6 },
    input: { borderRadius: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, color: colors.text, paddingHorizontal: 12, paddingVertical: 11, fontSize: 14, marginBottom: 12 },
    categoryGrid: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 12 },
    chip: { backgroundColor: colors.surfaceMuted, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 10, marginRight: 8, marginBottom: 8, borderWidth: 1, borderColor: colors.border, minWidth: 84, alignItems: 'center' },
    chipSelected: { backgroundColor: colors.primarySoft, borderColor: colors.primary },
    chipText: { fontWeight: '700', color: colors.muted, fontSize: 12 },
    chipTextSelected: { color: colors.onSoft },
    customManageBlock: { marginBottom: 10 },
    customManageLabel: { fontSize: 11, color: colors.muted, fontWeight: '700', marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.6 },
    customManageList: { gap: 8 },
    customManageRow: { borderWidth: 1, borderColor: colors.border, borderRadius: 10, backgroundColor: colors.surfaceMuted, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 10, paddingVertical: 8 },
    customManageSelect: { flex: 1, marginRight: 8 },
    customManageText: { color: colors.text, fontSize: 12, fontWeight: '700' },
    customManageDelete: { borderWidth: 1, borderColor: '#DC2626', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 4, backgroundColor: 'rgba(220,38,38,0.1)' },
    customManageDeleteText: { color: '#DC2626', fontSize: 11, fontWeight: '800' },
    customCategoryInput: { marginTop: -2, marginBottom: 8 },
    saveCategoryButton: { borderRadius: 10, borderWidth: 1, borderColor: colors.primary, backgroundColor: colors.primarySoft, paddingVertical: 10, alignItems: 'center', marginBottom: 8 },
    saveCategoryText: { color: colors.onSoft, fontSize: 12, fontWeight: '800' },
    disabledButton: { opacity: 0.6 },
  });

export const createHistoryStyles = (colors) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: colors.background },
    container: { flex: 1, paddingHorizontal: 16, paddingTop: 14 },
    heroCard: { borderRadius: 24, backgroundColor: colors.primary, paddingHorizontal: 16, paddingVertical: 16, overflow: 'hidden' },
    heroGlowOne: { position: 'absolute', width: 170, height: 170, borderRadius: 85, top: -90, left: -45, opacity: 0.4 },
    heroGlowTwo: { position: 'absolute', width: 180, height: 180, borderRadius: 90, bottom: -90, right: -40, opacity: 0.34 },
    heroCaption: { color: 'rgba(255,255,255,0.84)', fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.8 },
    heroTitle: { marginTop: 4, color: colors.onPrimary, fontSize: 23, fontWeight: '900' },
    heroStatsRow: { marginTop: 12, flexDirection: 'row', gap: 9 },
    heroPill: { flex: 1, borderRadius: 14, padding: 10, backgroundColor: 'rgba(255,255,255,0.18)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.24)' },
    heroPillLabel: { color: 'rgba(255,255,255,0.88)', fontSize: 10, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.7 },
    heroPillValue: { marginTop: 4, color: colors.onPrimary, fontSize: 14, fontWeight: '800' },
    listContent: { paddingBottom: 120, paddingTop: 2 },
    emptyCard: { marginTop: 6, borderRadius: 16, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, padding: 14 },
    emptyTitle: { color: colors.text, fontWeight: '800', fontSize: 13 },
    emptyText: { marginTop: 6, color: colors.muted, fontSize: 12 },
  });

export const createPortfolioStyles = (colors) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: colors.background },
    container: { flex: 1, paddingHorizontal: 16, paddingTop: 14 },
    heroCard: { borderRadius: 24, backgroundColor: colors.primary, paddingHorizontal: 16, paddingVertical: 16, overflow: 'hidden' },
    heroGlowOne: { position: 'absolute', width: 170, height: 170, borderRadius: 85, top: -90, left: -44, opacity: 0.4 },
    heroGlowTwo: { position: 'absolute', width: 170, height: 170, borderRadius: 85, bottom: -88, right: -36, opacity: 0.35 },
    heroCaption: { color: 'rgba(255,255,255,0.84)', fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.7 },
    heroTitle: { marginTop: 5, color: colors.onPrimary, fontSize: 22, fontWeight: '900' },
    heroMeta: { marginTop: 5, color: 'rgba(255,255,255,0.85)', fontSize: 12 },
    heroPill: { marginTop: 12, borderRadius: 14, padding: 10, backgroundColor: 'rgba(255,255,255,0.18)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.28)' },
    heroPillLabel: { color: 'rgba(255,255,255,0.88)', fontSize: 10, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.7 },
    heroPillValue: { marginTop: 4, color: colors.onPrimary, fontSize: 16, fontWeight: '900' },
    listContent: { paddingBottom: 20 },
    assetCard: { marginTop: 10, borderRadius: 16, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, paddingVertical: 12, paddingHorizontal: 14, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    assetCode: { fontWeight: '800', fontSize: 15, color: colors.text },
    assetValue: { fontWeight: '800', fontSize: 15, color: colors.primary },
    emptyCard: { marginTop: 10, borderRadius: 16, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, padding: 14 },
    emptyTitle: { color: colors.text, fontWeight: '800', fontSize: 13 },
    emptyText: { marginTop: 6, color: colors.muted, fontSize: 12 },
  });

export const createCategoryStatsStyles = (colors) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: colors.background },
    scrollContent: { paddingHorizontal: 16, paddingTop: 14, paddingBottom: 30 },
    heroCard: { borderRadius: 24, backgroundColor: colors.primary, paddingHorizontal: 16, paddingVertical: 16, overflow: 'hidden', marginBottom: 12 },
    heroGlowOne: { position: 'absolute', width: 170, height: 170, borderRadius: 85, top: -90, left: -44, opacity: 0.4 },
    heroGlowTwo: { position: 'absolute', width: 170, height: 170, borderRadius: 85, bottom: -88, right: -36, opacity: 0.35 },
    heroCaption: { color: 'rgba(255,255,255,0.84)', fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.7 },
    heroTitle: { marginTop: 5, color: colors.onPrimary, fontSize: 22, fontWeight: '900' },
    heroMeta: { marginTop: 5, color: 'rgba(255,255,255,0.85)', fontSize: 12 },
    card: { backgroundColor: colors.surface, borderRadius: 20, padding: 16, borderWidth: 1, borderColor: colors.border, alignItems: 'center' },
    centerLabel: { position: 'absolute', top: 106, alignItems: 'center' },
    centerLabelTitle: { color: colors.muted, fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.8 },
    centerLabelValue: { color: colors.text, fontSize: 18, fontWeight: '900' },
    legend: { marginTop: 18, width: '100%' },
    legendRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: colors.border },
    colorDot: { width: 12, height: 12, borderRadius: 6, marginRight: 12 },
    legendLabel: { flex: 1, color: colors.text, fontWeight: '700', fontSize: 13 },
    legendValue: { color: colors.muted, fontWeight: '800', fontSize: 12 },
    emptyState: { backgroundColor: colors.surface, borderRadius: 20, borderWidth: 1, borderColor: colors.border, padding: 18, marginTop: 4 },
    emptyTitle: { color: colors.text, fontSize: 15, fontWeight: '800', marginBottom: 6 },
    emptyText: { color: colors.muted, fontSize: 13 },
  });

export const createGoalsStyles = (colors) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: colors.background },
    scrollContent: { paddingHorizontal: 16, paddingTop: 14, paddingBottom: 30 },
    heroCard: { borderRadius: 24, backgroundColor: colors.primary, paddingHorizontal: 16, paddingVertical: 16, marginBottom: 14, overflow: 'hidden' },
    heroGlowOne: { position: 'absolute', width: 170, height: 170, borderRadius: 85, top: -90, left: -44, opacity: 0.4 },
    heroGlowTwo: { position: 'absolute', width: 170, height: 170, borderRadius: 85, bottom: -86, right: -36, opacity: 0.35 },
    heroCaption: { color: 'rgba(255,255,255,0.84)', fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.8 },
    heroTitle: { marginTop: 5, color: colors.onPrimary, fontSize: 23, fontWeight: '900' },
    heroMeta: { marginTop: 5, color: 'rgba(255,255,255,0.84)', fontSize: 12 },
    progressTrack: { marginTop: 12, height: 10, borderRadius: 6, backgroundColor: 'rgba(255,255,255,0.24)', overflow: 'hidden' },
    progressFill: { height: '100%', borderRadius: 6, backgroundColor: '#FFFFFF' },
    heroStats: { marginTop: 12, flexDirection: 'row', gap: 9 },
    heroStatPill: { flex: 1, borderRadius: 14, padding: 10, backgroundColor: 'rgba(255,255,255,0.17)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.26)' },
    heroStatLabel: { color: 'rgba(255,255,255,0.88)', fontSize: 10, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.8 },
    heroStatValue: { marginTop: 5, color: colors.onPrimary, fontSize: 14, fontWeight: '800' },
    loadingBox: { borderRadius: 16, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, paddingVertical: 14, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
    loadingText: { marginLeft: 10, color: colors.muted, fontWeight: '600' },
    card: { borderRadius: 20, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, padding: 14, marginBottom: 12 },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    cardTitle: { color: colors.text, fontSize: 16, fontWeight: '800', marginBottom: 10 },
    row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
    rowLast: { marginBottom: 0 },
    rowLabel: { color: colors.muted, fontSize: 13, fontWeight: '600' },
    rowValue: { color: colors.text, fontSize: 13, fontWeight: '800' },
    positiveValue: { color: '#16A34A' },
    negativeValue: { color: '#E11D48' },
    tipRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 9 },
    tipDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: colors.primary, marginTop: 6, marginRight: 8 },
    tipText: { flex: 1, color: colors.muted, fontSize: 13, lineHeight: 18 },
    input: { borderRadius: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, color: colors.text, paddingHorizontal: 12, paddingVertical: 11, fontSize: 14, marginBottom: 10 },
    primaryButton: { marginTop: 2, borderRadius: 12, backgroundColor: colors.primary, alignItems: 'center', paddingVertical: 12 },
    primaryButtonText: { color: colors.onPrimary, fontWeight: '800', fontSize: 13 },
    emptyText: { color: colors.muted, fontSize: 13 },
    goalCard: { borderRadius: 16, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceMuted, padding: 12, marginBottom: 10 },
    goalHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10, alignItems: 'center' },
    goalHeaderRight: { alignItems: 'flex-end' },
    goalTitle: { color: colors.text, fontSize: 14, fontWeight: '800' },
    goalMeta: { marginTop: 3, fontSize: 11, color: colors.muted },
    goalPercent: { color: colors.primary, fontSize: 13, fontWeight: '800' },
    deleteGoalButton: { marginTop: 6, borderWidth: 1, borderColor: '#DC2626', borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4, backgroundColor: 'rgba(220,38,38,0.1)' },
    deleteGoalButtonText: { color: '#DC2626', fontSize: 10, fontWeight: '800' },
    goalProgressTrack: { height: 9, borderRadius: 6, backgroundColor: 'rgba(148,163,184,0.28)', overflow: 'hidden' },
    goalProgressFill: { height: '100%', borderRadius: 6, backgroundColor: colors.primary },
    goalAmount: { marginTop: 8, color: colors.text, fontSize: 12, fontWeight: '700' },
    contributionRow: { flexDirection: 'row', alignItems: 'center', marginTop: 8 },
    contributionInput: { flex: 1, marginBottom: 0, marginRight: 8 },
    secondaryButton: { borderRadius: 10, backgroundColor: colors.primarySoft, borderWidth: 1, borderColor: colors.primary, paddingVertical: 10, paddingHorizontal: 14 },
    secondaryButtonText: { color: colors.onSoft, fontSize: 12, fontWeight: '800' },
  });

export const createRemindersStyles = (colors) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: colors.background },
    scrollContent: { paddingHorizontal: 16, paddingTop: 14, paddingBottom: 30 },
    heroCard: { borderRadius: 24, backgroundColor: colors.primary, paddingHorizontal: 16, paddingVertical: 16, marginBottom: 12, overflow: 'hidden' },
    heroGlowOne: { position: 'absolute', width: 166, height: 166, borderRadius: 83, top: -90, left: -42, opacity: 0.42 },
    heroGlowTwo: { position: 'absolute', width: 170, height: 170, borderRadius: 85, bottom: -90, right: -34, opacity: 0.34 },
    heroCaption: { color: 'rgba(255,255,255,0.82)', fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.7 },
    heroTitle: { marginTop: 5, color: colors.onPrimary, fontSize: 22, fontWeight: '900' },
    heroMeta: { marginTop: 5, color: 'rgba(255,255,255,0.85)', fontSize: 12 },
    statsRow: { marginTop: 12, flexDirection: 'row', gap: 9 },
    statPill: { flex: 1, borderRadius: 14, padding: 10, backgroundColor: 'rgba(255,255,255,0.17)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.28)' },
    statLabel: { color: 'rgba(255,255,255,0.9)', fontSize: 10, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.7 },
    statValue: { marginTop: 5, color: colors.onPrimary, fontSize: 14, fontWeight: '800' },
    card: { borderRadius: 20, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, padding: 14, marginBottom: 12 },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    cardTitle: { color: colors.text, fontSize: 16, fontWeight: '800', marginBottom: 10 },
    input: { borderRadius: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, color: colors.text, paddingHorizontal: 12, paddingVertical: 11, fontSize: 14, marginBottom: 10 },
    primaryButton: { marginTop: 2, borderRadius: 12, backgroundColor: colors.primary, alignItems: 'center', paddingVertical: 12 },
    primaryButtonText: { color: colors.onPrimary, fontWeight: '800', fontSize: 13 },
    emptyText: { color: colors.muted, fontSize: 13 },
    reminderCard: { borderRadius: 16, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceMuted, padding: 12, marginBottom: 10 },
    reminderDone: { backgroundColor: '#F0FDF4', borderColor: '#BBF7D0' },
    reminderHead: { flexDirection: 'row', alignItems: 'center' },
    reminderTitle: { color: colors.text, fontSize: 14, fontWeight: '800' },
    reminderDate: { marginTop: 3, color: colors.muted, fontSize: 12 },
    badge: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5, marginLeft: 10 },
    badgeText: { fontSize: 11, fontWeight: '800' },
    reminderBottom: { marginTop: 10, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    reminderActions: { alignItems: 'flex-end' },
    markPaidButton: { borderRadius: 8, paddingHorizontal: 4, paddingVertical: 2 },
    reminderAmount: { color: colors.text, fontSize: 13, fontWeight: '700' },
    reminderAction: { color: colors.primary, fontSize: 11, fontWeight: '700' },
    deleteReminderButton: { marginTop: 6, borderWidth: 1, borderColor: '#DC2626', borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4, backgroundColor: 'rgba(220,38,38,0.1)' },
    deleteReminderButtonText: { color: '#DC2626', fontSize: 10, fontWeight: '800' },
  });

export const createProfileStyles = (colors) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: colors.background },
    scrollContent: { paddingHorizontal: 16, paddingTop: 14, paddingBottom: 130 },
    topHeader: { marginBottom: 14 },
    title: { fontSize: 27, fontWeight: '800', color: colors.text },
    heroCard: { borderRadius: 24, backgroundColor: colors.primary, paddingHorizontal: 16, paddingVertical: 18, alignItems: 'center', overflow: 'hidden', marginBottom: 16 },
    heroGlowOne: { position: 'absolute', width: 170, height: 170, borderRadius: 85, top: -80, left: -45, opacity: 0.42 },
    heroGlowTwo: { position: 'absolute', width: 180, height: 180, borderRadius: 90, bottom: -90, right: -40, opacity: 0.35 },
    heroAvatarRing: { width: 74, height: 74, borderRadius: 37, backgroundColor: colors.surface, justifyContent: 'center', alignItems: 'center', marginBottom: 8 },
    heroAvatar: { width: 68, height: 68, borderRadius: 34, backgroundColor: colors.primarySoft, justifyContent: 'center', alignItems: 'center' },
    heroAvatarText: { fontSize: 22, fontWeight: '900', color: colors.primary },
    heroName: { color: colors.onPrimary, fontSize: 17, fontWeight: '800' },
    heroEmail: { marginTop: 3, color: 'rgba(255,255,255,0.85)', fontSize: 12 },
    loadingWrap: { backgroundColor: colors.surface, borderRadius: 16, borderWidth: 1, borderColor: colors.border, padding: 14, marginBottom: 12, flexDirection: 'row', alignItems: 'center', gap: 10 },
    loadingText: { fontSize: 13, color: colors.muted, fontWeight: '600' },
    section: { marginBottom: 14 },
    sectionTitle: { fontSize: 12, fontWeight: '800', color: colors.muted, textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 8 },
    sectionHint: { color: colors.muted, fontSize: 12, marginBottom: 8 },
    fieldLabel: { fontSize: 12, fontWeight: '700', color: colors.text, marginBottom: 6 },
    input: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 13, paddingHorizontal: 12, paddingVertical: 11, fontSize: 14, color: colors.text, marginBottom: 10 },
    bioInput: { minHeight: 88, textAlignVertical: 'top' },
    counterText: { fontSize: 11, color: colors.muted, textAlign: 'right', marginTop: -4 },
    autosaveText: { color: colors.muted, fontSize: 11, marginTop: -4, marginBottom: 8 },
    themeRow: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 10 },
    themeChip: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 999, paddingHorizontal: 14, paddingVertical: 8, marginRight: 8, marginBottom: 8 },
    themeChipSelected: { backgroundColor: colors.primarySoft, borderColor: colors.primary },
    themeChipText: { color: colors.muted, fontSize: 12, fontWeight: '700' },
    themeChipTextSelected: { color: colors.onSoft },
    toggleRow: { backgroundColor: colors.surface, borderRadius: 14, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 12, paddingVertical: 12, marginBottom: 8, flexDirection: 'row', alignItems: 'center', gap: 12 },
    toggleTitle: { fontSize: 13, fontWeight: '700', color: colors.text },
    toggleMeta: { marginTop: 4, color: colors.muted, fontSize: 11 },
    row: { backgroundColor: colors.surface, borderRadius: 14, borderWidth: 1, borderColor: colors.border, paddingVertical: 12, paddingHorizontal: 14, marginBottom: 8 },
    rowTitle: { fontSize: 13, fontWeight: '700', color: colors.text },
    rowMeta: { fontSize: 11, color: colors.muted, marginTop: 4 },
    secondaryButton: { backgroundColor: colors.primarySoft, borderColor: colors.primary, marginTop: 2 },
    disabledButton: { opacity: 0.5 },
    logoutButton: { backgroundColor: colors.text, borderRadius: 12, paddingVertical: 12, alignItems: 'center', marginTop: 6 },
    logoutText: { color: '#FFFFFF', fontWeight: '700', fontSize: 13 },
  });

export const createLeaderboardStyles = (colors) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: colors.background },
    scrollContent: { paddingHorizontal: 16, paddingTop: 14, paddingBottom: 30 },
    heroCard: { borderRadius: 24, backgroundColor: colors.primary, paddingHorizontal: 16, paddingVertical: 16, marginBottom: 14, overflow: 'hidden' },
    heroGlowOne: { position: 'absolute', width: 170, height: 170, borderRadius: 85, top: -90, left: -44, opacity: 0.4 },
    heroGlowTwo: { position: 'absolute', width: 170, height: 170, borderRadius: 85, bottom: -88, right: -36, opacity: 0.35 },
    heroCaption: { color: 'rgba(255,255,255,0.84)', fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.7 },
    heroTitle: { marginTop: 5, color: colors.onPrimary, fontSize: 22, fontWeight: '900' },
    heroMeta: { marginTop: 5, color: 'rgba(255,255,255,0.85)', fontSize: 12 },
    heroPill: { marginTop: 12, borderRadius: 14, padding: 10, backgroundColor: 'rgba(255,255,255,0.17)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.28)' },
    heroPillLabel: { color: 'rgba(255,255,255,0.88)', fontSize: 10, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.7 },
    heroPillValue: { marginTop: 5, color: colors.onPrimary, fontSize: 16, fontWeight: '900' },
    metricRow: { flexDirection: 'row', marginBottom: 12, gap: 8 },
    metricChip: { flex: 1, borderRadius: 999, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, paddingVertical: 9, alignItems: 'center' },
    metricChipActive: { borderColor: colors.primary, backgroundColor: colors.primarySoft },
    metricChipText: { fontSize: 12, fontWeight: '700', color: colors.muted },
    metricChipTextActive: { color: colors.onSoft },
    loadingWrap: { marginBottom: 12, borderRadius: 16, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 9 },
    loadingText: { color: colors.muted, fontSize: 12, fontWeight: '600' },
    emptyCard: { borderRadius: 16, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, padding: 14 },
    emptyTitle: { color: colors.text, fontSize: 14, fontWeight: '800' },
    emptyText: { marginTop: 6, color: colors.muted, fontSize: 12 },
    userCard: { borderRadius: 16, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, padding: 12, marginBottom: 10 },
    userTopRow: { flexDirection: 'row', alignItems: 'center' },
    rankBubble: { width: 34, height: 34, borderRadius: 17, backgroundColor: colors.primarySoft, borderWidth: 1, borderColor: colors.primary, alignItems: 'center', justifyContent: 'center', marginRight: 10 },
    rankText: { color: colors.onSoft, fontSize: 11, fontWeight: '800' },
    userName: { color: colors.text, fontSize: 13, fontWeight: '800' },
    userDisplayName: { marginTop: 2, color: colors.muted, fontSize: 11 },
    metricLabel: { color: colors.muted, fontSize: 10, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.6 },
    metricValue: { marginTop: 4, color: colors.primary, fontSize: 12, fontWeight: '800' },
    userBottomRow: { marginTop: 10, paddingTop: 9, borderTopWidth: 1, borderTopColor: colors.border, flexDirection: 'row', justifyContent: 'space-between', gap: 8 },
    userMeta: { color: colors.muted, fontSize: 11, fontWeight: '600' },
  });

export const createAppButtonStyles = (colors) =>
  StyleSheet.create({
    button: { paddingVertical: 12, paddingHorizontal: 16, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginVertical: 6, elevation: 4, shadowColor: '#000', shadowOpacity: 0.2, shadowRadius: 5, shadowOffset: { width: 0, height: 2 } },
    primaryButton: { backgroundColor: colors.primary, borderWidth: 1, borderColor: colors.primary },
    secondaryButton: { backgroundColor: 'transparent', borderWidth: 2, borderColor: colors.primary },
    text: { fontSize: 14, fontWeight: '700', letterSpacing: 0.5 },
    primaryText: { color: '#FFFFFF' },
    secondaryText: { color: colors.primary },
  });

export const createTransactionItemStyles = (colors) =>
  StyleSheet.create({
    cardRow: { flexDirection: 'row', alignItems: 'flex-start', padding: 12, marginBottom: 9, borderRadius: 14, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
    dot: { width: 10, height: 10, borderRadius: 5, marginTop: 4, marginRight: 9 },
    content: { flex: 1 },
    deleteButton: { marginLeft: 10, alignSelf: 'center', borderWidth: 1, borderColor: '#DC2626', backgroundColor: 'rgba(220,38,38,0.1)', borderRadius: 8, paddingHorizontal: 8, paddingVertical: 5 },
    deleteButtonDisabled: { opacity: 0.6 },
    deleteText: { color: '#DC2626', fontSize: 11, fontWeight: '800' },
    title: { fontWeight: '800', color: colors.text, marginBottom: 4, fontSize: 13 },
    metaRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 },
    metaText: { color: colors.muted, fontSize: 11 },
    metaStrong: { fontWeight: '800', color: colors.text },
    dateText: { fontSize: 10, color: colors.muted, marginTop: 6 },
  });

export const createBottomNavStyles = (colors) =>
  StyleSheet.create({
    wrapper: { position: 'absolute', left: 12, right: 12, bottom: 0 },
    nav: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 8, paddingHorizontal: 8, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 24, shadowColor: '#111827', shadowOpacity: 0.08, shadowRadius: 16, shadowOffset: { width: 0, height: 6 }, elevation: 6 },
    tabButton: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 6, borderRadius: 16 },
    tabButtonActive: { backgroundColor: colors.primarySoft },
    tabLabel: { marginTop: 3, fontSize: 10, fontWeight: '700', color: colors.muted },
    tabLabelActive: { color: colors.primary },
    profileMiniRing: { width: 26, height: 26, borderRadius: 13, backgroundColor: colors.secondary, padding: 1.5, justifyContent: 'center', alignItems: 'center' },
    profileMiniRingActive: { backgroundColor: colors.primary },
    profileMiniInner: { width: 22, height: 22, borderRadius: 11, backgroundColor: colors.surface, justifyContent: 'center', alignItems: 'center' },
    profileMiniText: { fontSize: 9, fontWeight: '900', color: colors.secondary },
    profileMiniTextActive: { color: colors.primary },
  });

export const createAppToastHostStyles = (colors) =>
  StyleSheet.create({
    container: { ...StyleSheet.absoluteFillObject, alignItems: 'center', justifyContent: 'center', zIndex: 9999, paddingHorizontal: 14 },
    toast: { width: '100%', maxWidth: 460, borderRadius: 16, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, paddingHorizontal: 14, paddingVertical: 12, shadowColor: '#000000', shadowOpacity: 0.12, shadowRadius: 14, shadowOffset: { width: 0, height: 5 }, elevation: 5 },
    title: { fontSize: 13, fontWeight: '800', color: colors.text },
    message: { marginTop: 2, fontSize: 12, color: colors.muted },
  });

